import React from 'react';

export const styles: { [key: string]: React.CSSProperties } = {
  dashboardContainer: { display: 'flex', minHeight: '100vh', backgroundColor: '#f4f6f9', position: 'relative' },
  mobileOverlay: { position: 'fixed', top: 0, left: 0, right: 0, bottom: 0, backgroundColor: 'rgba(0, 0, 0, 0.4)', zIndex: 1015 },
  sidebar: { width: '280px', backgroundColor: '#F4A623', color: '#ffffff', display: 'flex', flexDirection: 'column', position: 'fixed', top: 0, bottom: 0, left: 0, zIndex: 1010, boxShadow: '4px 0 25px rgba(0, 0, 0, 0.05)', overflowY: 'auto' },
  sidebarHeader: { padding: '28px 20px', display: 'flex', alignItems: 'center', gap: '4px', borderBottom: '1px solid rgba(255, 255, 255, 0.15)' },
  sidebarLogoFrame: { width: '72px', height: '72px', overflow: 'hidden', flexShrink: 0, display: 'flex', alignItems: 'center', justifyContent: 'center' },
  sidebarLogo: { width: '162px', height: '74px', objectFit: 'cover', objectPosition: '56% center', filter: 'brightness(0) invert(1)', flexShrink: 0 },
  sidebarTitle: { fontSize: '21px', fontWeight: 800, letterSpacing: '-0.5px', margin: 0, marginLeft: '-4px', transform: 'translateY(6px)' },
  sidebarNav: { padding: '24px 16px', display: 'flex', flexDirection: 'column', flexGrow: 1 },
  navList: { listStyle: 'none', padding: 0, margin: 0, display: 'flex', flexDirection: 'column', gap: '8px' },
  navListItem: { margin: 0, padding: 0 },
  navItem: { width: '100%', padding: '14px 20px', backgroundColor: 'transparent', border: 'none', borderRadius: '12px', color: 'rgba(255, 255, 255, 0.85)', fontSize: '15px', fontWeight: 600, cursor: 'pointer', display: 'flex', alignItems: 'center', textAlign: 'left', transition: 'all 0.2s ease' },
  navItemActive: { backgroundColor: '#ffffff', color: '#F4A623', boxShadow: '0 8px 16px rgba(0,0,0,0.06)' },
  sidebarFooter: { padding: '24px 16px', borderTop: '1px solid rgba(255, 255, 255, 0.15)' },
  btnLogout: { width: '100%', padding: '14px 20px', backgroundColor: 'rgba(255, 255, 255, 0.1)', border: '1px solid rgba(255, 255, 255, 0.2)', borderRadius: '12px', color: '#ffffff', fontSize: '15px', fontWeight: 700, cursor: 'pointer', display: 'flex', alignItems: 'center', justifyContent: 'center', transition: 'all 0.2s ease' },
  mainContent: { flexGrow: 1, paddingLeft: '280px', display: 'flex', flexDirection: 'column', minWidth: 0 },
  headerBar: { height: '76px', backgroundColor: '#ffffff', borderBottom: '1px solid #e2e8f0', padding: '0 32px', display: 'flex', alignItems: 'center', justifyContent: 'space-between', position: 'sticky', top: 0, zIndex: 1000 },
  headerKiri: { display: 'flex', alignItems: 'center', gap: '16px' },
  btnHamburger: { display: 'flex', alignItems: 'center', justifyContent: 'center', background: 'none', border: 'none', cursor: 'pointer', color: '#2d3748', padding: '8px', borderRadius: '8px', backgroundColor: '#f1f5f9' },
  headerGreeting: { fontSize: '22px', fontWeight: 800, color: '#2d3748', margin: 0 },
  headerKanan: { display: 'flex', alignItems: 'center', gap: '24px' },
  statsIconGroup: { display: 'flex', gap: '12px' },
  statBadge: { fontSize: '13px', fontWeight: 700, backgroundColor: '#fef3c7', color: '#d97706', padding: '8px 14px', borderRadius: '100px' },
  statBadgeAmber: { fontSize: '13px', fontWeight: 700, backgroundColor: '#eff6ff', color: '#3b82f6', padding: '8px 14px', borderRadius: '100px' },
  profilInfo: { display: 'flex', alignItems: 'center', gap: '12px' },
  avatarMini: { width: '40px', height: '40px', borderRadius: '50%', backgroundColor: '#F4A623', color: '#ffffff', display: 'flex', alignItems: 'center', justifyContent: 'center', fontWeight: 800, fontSize: '14px', boxShadow: '0 4px 12px rgba(244, 166, 35, 0.2)' },
  contentBody: { padding: '32px', display: 'flex', flexDirection: 'column', maxWidth: '1200px', width: '100%', margin: '0 auto' },
  bannerInfo: { background: 'linear-gradient(135deg, #F4A623 0%, #d97706 100%)', borderRadius: '24px', padding: '32px', display: 'flex', alignItems: 'center', justifyContent: 'space-between', gap: '24px', flexWrap: 'wrap', boxShadow: '0 10px 30px rgba(244, 166, 35, 0.15)', marginBottom: '32px' },
  bannerTeks: { color: '#ffffff', flex: 1, minWidth: '280px' },
  bannerJudul: { fontSize: '24px', fontWeight: 850, margin: '0 0 10px 0', lineHeight: 1.2 },
  bannerSubjudul: { fontSize: '14px', color: 'rgba(255, 255, 255, 0.85)', margin: 0, lineHeight: 1.5 },
  btnBannerCta: { backgroundColor: '#ffffff', color: '#d97706', border: 'none', borderRadius: '14px', padding: '14px 28px', fontWeight: 700, fontSize: '15px', cursor: 'pointer', boxShadow: '0 6px 20px rgba(0,0,0,0.06)', transition: 'all 0.2s ease' },
  cardsGrid: { display: 'grid', gridTemplateColumns: 'repeat(3, 1fr)', gap: '24px', marginBottom: '32px' },
  kartuUtama: { backgroundColor: '#ffffff', borderRadius: '24px', padding: '28px', boxShadow: '0 4px 20px rgba(0, 0, 0, 0.02)', border: '1px solid #e2e8f0', display: 'flex', flexDirection: 'column' },
  kartuJudul: { fontSize: '16px', fontWeight: 800, color: '#2d3748', margin: '0 0 20px 0' },
  levelWrapper: { display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '12px' },
  levelBadge: { fontSize: '12px', fontWeight: 800, backgroundColor: 'rgba(244, 166, 35, 0.1)', color: '#d97706', padding: '6px 12px', borderRadius: '8px' },
  levelXp: { fontSize: '13px', fontWeight: 700, color: '#718096' },
  progressBarBg: { height: '10px', backgroundColor: '#e2e8f0', borderRadius: '100px', overflow: 'hidden', marginBottom: '16px' },
  progressBarFill: { height: '100%', backgroundColor: '#F4A623', borderRadius: '100px', transition: 'width 0.4s ease-out' },
  xpInfo: { fontSize: '13px', color: '#718096', margin: 0, lineHeight: 1.4 },
  questHeader: { display: 'flex', justifyContent: 'space-between', fontSize: '13px', fontWeight: 700, color: '#718096', marginBottom: '8px' },
  questProgressTeks: { color: '#2d3748' },
  questPersen: { color: '#F4A623' },
  questList: { listStyle: 'none', padding: 0, margin: 0, display: 'flex', flexDirection: 'column', gap: '12px' },
  questItem: { display: 'flex', alignItems: 'flex-start', gap: '10px' },
  questCheckSelesai: { color: '#10b981', fontWeight: 800, fontSize: '14px' },
  questCheckBelum: { color: '#a0aec0', fontWeight: 800, fontSize: '14px' },
  questItemTeksSelesai: { fontSize: '13px', color: '#a0aec0', textDecoration: 'line-through' },
  questItemTeksBelum: { fontSize: '13px', color: '#4a5568' },
  rekomendasiList: { display: 'flex', flexDirection: 'column', gap: '16px' },
  rekomendasiItem: { display: 'flex', justifyContent: 'space-between', alignItems: 'center', padding: '16px', backgroundColor: '#f8fafc', borderRadius: '16px', border: '1px solid #e2e8f0' },
  rekomendasiItemJudul: { fontSize: '14px', fontWeight: 750, color: '#2d3748', margin: '0 0 4px 0' },
  rekomendasiItemSub: { fontSize: '12px', color: '#718096', margin: 0 },
  xpBadge: { fontSize: '12px', fontWeight: 800, backgroundColor: '#ecfdf5', color: '#10b981', padding: '6px 12px', borderRadius: '8px' },
  sectionBawah: { width: '100%' },
  kartuLebar: { backgroundColor: '#ffffff', borderRadius: '24px', padding: '28px', boxShadow: '0 4px 20px rgba(0, 0, 0, 0.02)', border: '1px solid #e2e8f0' },
  riwayatWrapper: { display: 'flex', flexDirection: 'column', gap: '12px' },
  riwayatItem: { display: 'flex', justifyContent: 'space-between', alignItems: 'center', padding: '16px', borderBottom: '1px solid #f1f5f9' },
  riwayatInfoKiri: { display: 'flex', alignItems: 'center', gap: '16px' },
  ikonBukuKecil: {
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    width: '20px',
    height: '20px',
    color: '#6366f1',
    flexShrink: 0,
    opacity: 0.95,
  },
  riwayatJudulTeks: { fontSize: '14px', fontWeight: 750, color: '#2d3748', margin: '0 0 4px 0' },
  riwayatKategori: { fontSize: '12px', color: '#718096', margin: 0 },
  riwayatInfoKanan: { display: 'flex', alignItems: 'center' },
  skorBadge: { fontSize: '13px', fontWeight: 700, padding: '6px 14px', borderRadius: '100px' },
  emptyStateContainer: {
  display: 'flex',
  flexDirection: 'column' as const,
  alignItems: 'center',
  justifyContent: 'center',
  padding: '60px 20px',
  backgroundColor: '#ffffff',
  borderRadius: '24px',
  border: '1px solid #e2e8f0',
  textAlign: 'center' as const,
} as React.CSSProperties,

emptyIcon: {
  fontSize: '56px',
  marginBottom: '16px',
} as React.CSSProperties,

emptyTitle: {
  fontSize: '20px',
  fontWeight: 700,
  color: '#0f172a',
  margin: '0 0 8px 0',
} as React.CSSProperties,

emptyDesc: {
  fontSize: '15px',
  color: '#64748b',
  margin: '0 0 24px 0',
  maxWidth: '400px',
} as React.CSSProperties,

pilihMateriButton: {
  cursor: 'pointer',
  position: 'relative' as const,
  padding: '12px 32px',
  fontSize: '16px',
  color: '#F4A623',
  border: '2px solid #F4A623',
  borderRadius: '34px',
  backgroundColor: 'transparent',
  fontWeight: 700,
  transition: 'all 0.3s cubic-bezier(0.23, 1, 0.320, 1)',
  overflow: 'hidden',
  fontFamily: 'inherit',
} as React.CSSProperties,

skeletonCard: {
  backgroundColor: '#ffffff',
  borderRadius: '20px',
  overflow: 'hidden',
  border: '1px solid #e2e8f0',
  boxShadow: '0 4px 12px rgba(0, 0, 0, 0.04)',
} as React.CSSProperties,
};
